name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          "python:3.7",
          "python:3.8",
          "python:3.9",
          "python:3.10",
          "python:3.11",
          "python:3.12",
          "python:latest",
          "pypy:3.10"
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.python-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Print Python information
        run: python --version

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r extra.txt

      - name: Verify code format with black
        run: |
          pip install black
          black . --check

      - name: Verify code linting with pylint
        run: |
          pip install pylint
          cd src
          PYTHONPATH=. pylint --rcfile ../.pylintrc *
          cd ..
        if: matrix.python-version == 'python:3.12'

      - name: Verify code structure with mypy
        run: |
          pip install mypy
          mypy src --ignore-missing-imports --disable-error-code no-redef
          MYPYPATH=src mypy test --ignore-missing-imports --disable-error-code no-redef

      - name: Run unit tests
        run: |
          pip install pytest
          PYTHONPATH=src pytest
